# Generated by Django 5.0.7 on 2024-07-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
