# Generated by Django 5.0.7 on 2024-07-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_alter_employee_address_alter_employee_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
